import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // ============================
  // Categorías
  // ============================
  const categorias = await Promise.all([
    prisma.category.upsert({ where: { name: 'Analgésicos' }, update: {}, create: { name: 'Analgésicos' } }),
    prisma.category.upsert({ where: { name: 'Antibióticos' }, update: {}, create: { name: 'Antibióticos' } }),
    prisma.category.upsert({ where: { name: 'Antiinflamatorios' }, update: {}, create: { name: 'Antiinflamatorios' } }),
    prisma.category.upsert({ where: { name: 'Vitaminas y Suplementos' }, update: {}, create: { name: 'Vitaminas y Suplementos' } }),
    prisma.category.upsert({ where: { name: 'Antiparasitarios' }, update: {}, create: { name: 'Antiparasitarios' } }),
    prisma.category.upsert({ where: { name: 'Cardiovascular' }, update: {}, create: { name: 'Cardiovascular' } }),
    prisma.category.upsert({ where: { name: 'Dermatología' }, update: {}, create: { name: 'Dermatología' } }),
    prisma.category.upsert({ where: { name: 'Gastrointestinal' }, update: {}, create: { name: 'Gastrointestinal' } }),
  ]);

  const [analgesicos, antibioticos, antiinflamatorios, vitaminas, antiparasitarios, cardiovascular, dermatologia, gastrointestinal] = categorias;

  // ============================
  // Laboratorios
  // ============================
  const laboratorios = await Promise.all([
    prisma.laboratory.upsert({ where: { name: 'Bayer' }, update: {}, create: { name: 'Bayer' } }),
    prisma.laboratory.upsert({ where: { name: 'Pfizer' }, update: {}, create: { name: 'Pfizer' } }),
    prisma.laboratory.upsert({ where: { name: 'INTI (Bolivia)' }, update: {}, create: { name: 'INTI (Bolivia)' } }),
    prisma.laboratory.upsert({ where: { name: 'Genfar' }, update: {}, create: { name: 'Genfar' } }),
    prisma.laboratory.upsert({ where: { name: 'Roche' }, update: {}, create: { name: 'Roche' } }),
    prisma.laboratory.upsert({ where: { name: 'Novartis' }, update: {}, create: { name: 'Novartis' } }),
    prisma.laboratory.upsert({ where: { name: 'MK (Bolivia)' }, update: {}, create: { name: 'MK (Bolivia)' } }),
    prisma.laboratory.upsert({ where: { name: 'Merck' }, update: {}, create: { name: 'Merck' } }),
  ]);

  const [bayer, pfizer, inti, genfar, roche, novartis, mk, merck] = laboratorios;

  // ============================
  // Productos
  // ============================
  const productos = [
    {
      barcode: '7770001000001',
      internalCode: 'PROD-001',
      commercialName: 'Paracetamol 500mg x 20 comp.',
      genericName: 'Paracetamol',
      categoryId: analgesicos.id,
      laboratoryId: inti.id,
      pharmaceuticalForm: 'Comprimido',
      concentration: '500mg',
      activeIngredient: 'Paracetamol',
      measureUnit: 'CAJA',
      purchasePrice: 5.50,
      profitMargin: 30,
      salePrice1: 7.50,
      salePrice2: 7.00,
      salePrice3: 6.50,
      minDiscountPrice: 6.00,
      currentStock: 120,
      minStock: 20,
    },
    {
      barcode: '7770001000002',
      internalCode: 'PROD-002',
      commercialName: 'Ibuprofeno 400mg x 20 comp.',
      genericName: 'Ibuprofeno',
      categoryId: antiinflamatorios.id,
      laboratoryId: genfar.id,
      pharmaceuticalForm: 'Comprimido',
      concentration: '400mg',
      activeIngredient: 'Ibuprofeno',
      measureUnit: 'CAJA',
      purchasePrice: 8.00,
      profitMargin: 30,
      salePrice1: 11.00,
      salePrice2: 10.50,
      salePrice3: 10.00,
      minDiscountPrice: 9.50,
      currentStock: 85,
      minStock: 15,
    },
    {
      barcode: '7770001000003',
      internalCode: 'PROD-003',
      commercialName: 'Amoxicilina 500mg x 21 cáps.',
      genericName: 'Amoxicilina',
      categoryId: antibioticos.id,
      laboratoryId: pfizer.id,
      pharmaceuticalForm: 'Cápsula',
      concentration: '500mg',
      activeIngredient: 'Amoxicilina trihidrato',
      measureUnit: 'CAJA',
      purchasePrice: 22.00,
      profitMargin: 25,
      salePrice1: 28.50,
      salePrice2: 27.00,
      salePrice3: 26.00,
      minDiscountPrice: 25.00,
      currentStock: 60,
      minStock: 10,
      requiresPrescription: true,
    },
    {
      barcode: '7770001000004',
      internalCode: 'PROD-004',
      commercialName: 'Vitamina C 1000mg x 30 comp.',
      genericName: 'Ácido Ascórbico',
      categoryId: vitaminas.id,
      laboratoryId: bayer.id,
      pharmaceuticalForm: 'Comprimido efervescente',
      concentration: '1000mg',
      activeIngredient: 'Ácido Ascórbico',
      measureUnit: 'CAJA',
      purchasePrice: 18.00,
      profitMargin: 35,
      salePrice1: 25.00,
      salePrice2: 23.50,
      salePrice3: 22.00,
      minDiscountPrice: 21.00,
      currentStock: 45,
      minStock: 8,
    },
    {
      barcode: '7770001000005',
      internalCode: 'PROD-005',
      commercialName: 'Omeprazol 20mg x 14 cáps.',
      genericName: 'Omeprazol',
      categoryId: gastrointestinal.id,
      laboratoryId: mk.id,
      pharmaceuticalForm: 'Cápsula',
      concentration: '20mg',
      activeIngredient: 'Omeprazol',
      measureUnit: 'CAJA',
      purchasePrice: 12.00,
      profitMargin: 30,
      salePrice1: 16.00,
      salePrice2: 15.00,
      salePrice3: 14.50,
      minDiscountPrice: 14.00,
      currentStock: 70,
      minStock: 12,
    },
    {
      barcode: '7770001000006',
      internalCode: 'PROD-006',
      commercialName: 'Atorvastatina 20mg x 30 comp.',
      genericName: 'Atorvastatina',
      categoryId: cardiovascular.id,
      laboratoryId: pfizer.id,
      pharmaceuticalForm: 'Comprimido',
      concentration: '20mg',
      activeIngredient: 'Atorvastatina cálcica',
      measureUnit: 'CAJA',
      purchasePrice: 35.00,
      profitMargin: 25,
      salePrice1: 45.00,
      salePrice2: 43.00,
      salePrice3: 41.00,
      minDiscountPrice: 40.00,
      currentStock: 30,
      minStock: 5,
      requiresPrescription: true,
    },
    {
      barcode: '7770001000007',
      internalCode: 'PROD-007',
      commercialName: 'Metronidazol 500mg x 20 comp.',
      genericName: 'Metronidazol',
      categoryId: antibioticos.id,
      laboratoryId: inti.id,
      pharmaceuticalForm: 'Comprimido',
      concentration: '500mg',
      activeIngredient: 'Metronidazol',
      measureUnit: 'CAJA',
      purchasePrice: 9.00,
      profitMargin: 30,
      salePrice1: 12.00,
      salePrice2: 11.50,
      salePrice3: 11.00,
      minDiscountPrice: 10.50,
      currentStock: 50,
      minStock: 10,
      requiresPrescription: true,
    },
    {
      barcode: '7770001000008',
      internalCode: 'PROD-008',
      commercialName: 'Loratadina 10mg x 20 comp.',
      genericName: 'Loratadina',
      categoryId: analgesicos.id,
      laboratoryId: genfar.id,
      pharmaceuticalForm: 'Comprimido',
      concentration: '10mg',
      activeIngredient: 'Loratadina',
      measureUnit: 'CAJA',
      purchasePrice: 7.50,
      profitMargin: 30,
      salePrice1: 10.00,
      salePrice2: 9.50,
      salePrice3: 9.00,
      minDiscountPrice: 8.50,
      currentStock: 65,
      minStock: 10,
    },
    {
      barcode: '7770001000009',
      internalCode: 'PROD-009',
      commercialName: 'Albendazol 400mg x 2 comp.',
      genericName: 'Albendazol',
      categoryId: antiparasitarios.id,
      laboratoryId: mk.id,
      pharmaceuticalForm: 'Comprimido',
      concentration: '400mg',
      activeIngredient: 'Albendazol',
      measureUnit: 'CAJA',
      purchasePrice: 6.00,
      profitMargin: 40,
      salePrice1: 8.50,
      salePrice2: 8.00,
      salePrice3: 7.50,
      minDiscountPrice: 7.00,
      currentStock: 90,
      minStock: 20,
    },
    {
      barcode: '7770001000010',
      internalCode: 'PROD-010',
      commercialName: 'Diclofenaco 75mg Inyectable x 3 amp.',
      genericName: 'Diclofenaco sódico',
      categoryId: antiinflamatorios.id,
      laboratoryId: novartis.id,
      pharmaceuticalForm: 'Solución inyectable',
      concentration: '75mg/3ml',
      activeIngredient: 'Diclofenaco sódico',
      measureUnit: 'CAJA',
      purchasePrice: 14.00,
      profitMargin: 30,
      salePrice1: 18.50,
      salePrice2: 18.00,
      salePrice3: 17.50,
      minDiscountPrice: 17.00,
      currentStock: 40,
      minStock: 8,
      requiresPrescription: true,
    },
    {
      barcode: '7770001000011',
      internalCode: 'PROD-011',
      commercialName: 'Vitamina B12 1000mcg x 30 comp.',
      genericName: 'Cianocobalamina',
      categoryId: vitaminas.id,
      laboratoryId: merck.id,
      pharmaceuticalForm: 'Comprimido',
      concentration: '1000mcg',
      activeIngredient: 'Cianocobalamina',
      measureUnit: 'CAJA',
      purchasePrice: 15.00,
      profitMargin: 35,
      salePrice1: 21.00,
      salePrice2: 20.00,
      salePrice3: 19.00,
      minDiscountPrice: 18.00,
      currentStock: 55,
      minStock: 10,
    },
    {
      barcode: '7770001000012',
      internalCode: 'PROD-012',
      commercialName: 'Aspirina 100mg x 30 comp.',
      genericName: 'Ácido Acetilsalicílico',
      categoryId: cardiovascular.id,
      laboratoryId: bayer.id,
      pharmaceuticalForm: 'Comprimido',
      concentration: '100mg',
      activeIngredient: 'Ácido Acetilsalicílico',
      measureUnit: 'CAJA',
      purchasePrice: 6.50,
      profitMargin: 30,
      salePrice1: 8.50,
      salePrice2: 8.00,
      salePrice3: 7.50,
      minDiscountPrice: 7.00,
      currentStock: 100,
      minStock: 20,
    },
    {
      barcode: '7770001000013',
      internalCode: 'PROD-013',
      commercialName: 'Crema Clotrimazol 1% x 20g',
      genericName: 'Clotrimazol',
      categoryId: dermatologia.id,
      laboratoryId: genfar.id,
      pharmaceuticalForm: 'Crema dérmica',
      concentration: '1%',
      activeIngredient: 'Clotrimazol',
      measureUnit: 'TUBO',
      purchasePrice: 8.00,
      profitMargin: 40,
      salePrice1: 12.00,
      salePrice2: 11.50,
      salePrice3: 11.00,
      minDiscountPrice: 10.50,
      currentStock: 35,
      minStock: 6,
    },
    {
      barcode: '7770001000014',
      internalCode: 'PROD-014',
      commercialName: 'Losartan 50mg x 30 comp.',
      genericName: 'Losartán potásico',
      categoryId: cardiovascular.id,
      laboratoryId: merck.id,
      pharmaceuticalForm: 'Comprimido',
      concentration: '50mg',
      activeIngredient: 'Losartán potásico',
      measureUnit: 'CAJA',
      purchasePrice: 25.00,
      profitMargin: 25,
      salePrice1: 32.00,
      salePrice2: 31.00,
      salePrice3: 30.00,
      minDiscountPrice: 29.00,
      currentStock: 25,
      minStock: 5,
      requiresPrescription: true,
    },
    {
      barcode: '7770001000015',
      internalCode: 'PROD-015',
      commercialName: 'Metformina 850mg x 30 comp.',
      genericName: 'Metformina clorhidrato',
      categoryId: cardiovascular.id,
      laboratoryId: inti.id,
      pharmaceuticalForm: 'Comprimido',
      concentration: '850mg',
      activeIngredient: 'Metformina clorhidrato',
      measureUnit: 'CAJA',
      purchasePrice: 18.00,
      profitMargin: 25,
      salePrice1: 23.00,
      salePrice2: 22.00,
      salePrice3: 21.00,
      minDiscountPrice: 20.00,
      currentStock: 40,
      minStock: 8,
      requiresPrescription: true,
    },
    {
      barcode: '7770001000016',
      internalCode: 'PROD-016',
      commercialName: 'Ranitidina 150mg x 20 comp.',
      genericName: 'Ranitidina',
      categoryId: gastrointestinal.id,
      laboratoryId: mk.id,
      pharmaceuticalForm: 'Comprimido',
      concentration: '150mg',
      activeIngredient: 'Ranitidina clorhidrato',
      measureUnit: 'CAJA',
      purchasePrice: 7.00,
      profitMargin: 30,
      salePrice1: 9.50,
      salePrice2: 9.00,
      salePrice3: 8.50,
      minDiscountPrice: 8.00,
      currentStock: 75,
      minStock: 15,
    },
    {
      barcode: '7770001000017',
      internalCode: 'PROD-017',
      commercialName: 'Azitromicina 500mg x 3 comp.',
      genericName: 'Azitromicina',
      categoryId: antibioticos.id,
      laboratoryId: pfizer.id,
      pharmaceuticalForm: 'Comprimido',
      concentration: '500mg',
      activeIngredient: 'Azitromicina dihidrato',
      measureUnit: 'CAJA',
      purchasePrice: 28.00,
      profitMargin: 25,
      salePrice1: 36.00,
      salePrice2: 34.50,
      salePrice3: 33.00,
      minDiscountPrice: 32.00,
      currentStock: 45,
      minStock: 8,
      requiresPrescription: true,
    },
    {
      barcode: '7770001000018',
      internalCode: 'PROD-018',
      commercialName: 'Suero Oral Rehidratante x 500ml',
      genericName: 'Sales de rehidratación oral',
      categoryId: gastrointestinal.id,
      laboratoryId: inti.id,
      pharmaceuticalForm: 'Solución oral',
      concentration: 'OMS',
      activeIngredient: 'Cloruro de Sodio, Cloruro de Potasio, Glucosa',
      measureUnit: 'UNIDAD',
      purchasePrice: 4.00,
      profitMargin: 40,
      salePrice1: 5.80,
      salePrice2: 5.50,
      salePrice3: 5.20,
      minDiscountPrice: 5.00,
      currentStock: 80,
      minStock: 20,
    },
    {
      barcode: '7770001000019',
      internalCode: 'PROD-019',
      commercialName: 'Dexametasona 4mg/ml Iny. x 3 amp.',
      genericName: 'Dexametasona',
      categoryId: antiinflamatorios.id,
      laboratoryId: novartis.id,
      pharmaceuticalForm: 'Solución inyectable',
      concentration: '4mg/ml',
      activeIngredient: 'Dexametasona fosfato sódico',
      measureUnit: 'CAJA',
      purchasePrice: 16.00,
      profitMargin: 28,
      salePrice1: 21.00,
      salePrice2: 20.00,
      salePrice3: 19.00,
      minDiscountPrice: 18.50,
      currentStock: 30,
      minStock: 6,
      requiresPrescription: true,
    },
    {
      barcode: '7770001000020',
      internalCode: 'PROD-020',
      commercialName: 'Complejo B Forte x 60 comp.',
      genericName: 'Vitaminas B1, B6, B12',
      categoryId: vitaminas.id,
      laboratoryId: roche.id,
      pharmaceuticalForm: 'Comprimido',
      concentration: 'B1 100mg + B6 200mg + B12 200mcg',
      activeIngredient: 'Tiamina, Piridoxina, Cianocobalamina',
      measureUnit: 'FRASCO',
      purchasePrice: 22.00,
      profitMargin: 35,
      salePrice1: 30.00,
      salePrice2: 29.00,
      salePrice3: 28.00,
      minDiscountPrice: 27.00,
      currentStock: 50,
      minStock: 10,
    },
  ];

  let creados = 0;
  for (const p of productos) {
    // Evitar duplicar por código de barras
    const existing = await prisma.product.findUnique({ where: { barcode: p.barcode } });
    if (!existing) {
      await prisma.product.create({ data: p as any });
      creados++;
    }
  }

  console.log(`\n✅ Seed completado: ${creados} productos creados (${productos.length - creados} ya existían)\n`);
}

main()
  .catch((e) => {
    console.error('❌ Error en seed de productos:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
